title: Bryan Nsoh - AI & Biosystems Engineer
description: Automating intellectual labor with LLMs
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/images/profile.jpg  # You'll add this image later